# 난수 생성 함수

[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling


## random의 함수들

In [2]:
import random
print(random.random(),'\n') # 0.0<= x < 1.0 사이 난수 리턴

0.5483593644806206 



In [3]:
print(random.randint(1,10),'\n') # 1 <= x <= 10 사이의 정수중에서 난수 값 리턴 

8 



In [4]:
print(random.uniform(10,20),'\n') # min, max 사이 float 리턴, 끝값 포함

13.345568002091927 



In [5]:
print(random.randrange(10),'\n') # 지정 범위 int 리턴, range(10)의 값중에 하나를 return

8 



In [6]:
li = []
for i in range(100):
    li.append(random.randrange(8))
print(li, '\n')
set(li)

[4, 3, 3, 7, 5, 0, 1, 4, 1, 4, 5, 4, 7, 2, 1, 2, 5, 7, 0, 2, 4, 1, 7, 1, 6, 4, 4, 2, 2, 4, 7, 0, 5, 7, 1, 7, 4, 4, 2, 5, 4, 6, 3, 2, 6, 7, 3, 1, 2, 1, 7, 1, 3, 2, 5, 4, 5, 6, 4, 5, 1, 3, 6, 5, 4, 4, 2, 6, 2, 3, 0, 6, 7, 3, 7, 0, 0, 2, 5, 1, 0, 5, 1, 3, 3, 5, 6, 3, 0, 5, 6, 7, 5, 5, 3, 3, 5, 2, 5, 5] 



{0, 1, 2, 3, 4, 5, 6, 7}

In [7]:
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택

2 



In [8]:
li = [1,2,3,4,5]
print(random.sample(li, 3), '\n') # 리스트 요소를 중복이 안되게 리턴

[5, 2, 4] 



In [9]:
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

[1, 4, 2, 5, 3]


## numpy.random 함수들

In [10]:
import numpy as np
r = np.random.rand(100000000) # 0 ~ 1사이의 균일분포
# print(r)
r.mean()

0.5000297652199915

In [11]:
# 표준 정규분포
r = np.random.randn(10000)
print(r,'\n')
r.mean()

[-0.05538919  1.57471198  1.07141946 ... -0.96918889 -0.40851096
  0.65905814] 



-0.013539517783453527

In [12]:
np.random.uniform(1.0,2.0,10)

array([1.92800384, 1.28288049, 1.51904446, 1.01815358, 1.2719327 ,
       1.13980567, 1.89211086, 1.76619874, 1.18904452, 1.27088957])

In [13]:
np.random.uniform(0,1,(2,3)) # lower, upper, size

array([[0.5110205 , 0.03710661, 0.12981726],
       [0.00610606, 0.79794569, 0.46647963]])

In [14]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.21409032, 0.54016101, 0.6072198 ],
       [0.78714633, 0.63615907, 0.41287984]])

In [15]:
import pandas as pd
ar = np.random.rand(4,8)
ar

array([[0.3985904 , 0.10392247, 0.54359251, 0.82012481, 0.47576805,
        0.86501716, 0.0712399 , 0.97377798],
       [0.82503453, 0.98365797, 0.33011368, 0.19052842, 0.83709879,
        0.5475868 , 0.66596136, 0.33325685],
       [0.22134887, 0.05479394, 0.58199016, 0.88674147, 0.33620234,
        0.17958006, 0.11368834, 0.1502524 ],
       [0.92175821, 0.65681559, 0.96985055, 0.6370615 , 0.98984323,
        0.12595521, 0.26926071, 0.73914903]])

In [16]:
# 배열을 df로 변환
# coloumns 8개에 대한 이름# coloumns 8개에 대한 이름
columns = ['id','gender','age','region','product','price','qty','time']


In [17]:
df = pd.DataFrame(ar,columns=['id','gender','age','region','product','price','qty','time'])
df

id    gender       age    region   product     price       qty  \
0  0.398590  0.103922  0.543593  0.820125  0.475768  0.865017  0.071240   
1  0.825035  0.983658  0.330114  0.190528  0.837099  0.547587  0.665961   
2  0.221349  0.054794  0.581990  0.886741  0.336202  0.179580  0.113688   
3  0.921758  0.656816  0.969851  0.637062  0.989843  0.125955  0.269261   

       time  
0  0.973778  
1  0.333257  
2  0.150252  
3  0.739149

In [18]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df3를 출력하세요.

In [19]:
df.id = np.random.randint(10,99,4)
df.gender = np.random.choice(['male','female'],4)
df.age = np.random.randint(0,100,4)
df[['id','gender','age']]

id  gender  age
0  51  female   15
1  36  female   79
2  19    male   72
3  84  female   33

In [20]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_ar = np.random.randn(1000000)

In [21]:
large_ar

array([-1.27841094, -1.81911269, -1.34411608, ..., -2.35487923,
        0.99993347, -0.44849426])

In [22]:
large_ar.sort()

In [23]:
large_ar

array([-4.83127952, -4.64653388, -4.6441874 , ...,  4.5607412 ,
        4.58151594,  5.27472827])

In [24]:
large_ar[int(0.5*len(large_ar))] # int()의 arg는 내림처리된다.

-0.0005217024122117934

# 배열 집합 연산

In [25]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names), type(np.unique(names))

(array(['Bob', 'Joe', 'Will'], dtype='<U4'), numpy.ndarray)

In [26]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names)), type(sorted(set(names)))

(['Bob', 'Joe', 'Will'], list)

In [27]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환

val1 = np.array([6,0,0,3,2,5,6])
val2 = [2, 3, 6]
np.in1d(val1, val2)

array([ True, False, False,  True,  True, False,  True])

# 배열 데이터의 입출력

In [28]:
ar = np.arange(10)
np.save('some_ar',ar)

In [29]:
np.load('some_ar.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('ar_archive.npz', aim=ar, bob=ar) # aim, bob은 assign names (page name 같은거)

In [31]:
arch = np.load('ar_archive.npz')
arch['bob']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# np.argsort(array)

In [32]:
a = np.arange(1,10)
np.random.shuffle(a) # 참조

arg_sort = np.argsort(a)
print(a,'\n')
print(arg_sort,'\n')
print(a[arg_sort],'\n')

li_tup = []
for i in arg_sort:
    li_tup.append((a[i], i))
print(li_tup)
li_tup.sort()
print(li_tup)

[6 4 3 5 2 1 7 8 9] 

[5 4 2 1 3 0 6 7 8] 

[1 2 3 4 5 6 7 8 9] 

[(1, 5), (2, 4), (3, 2), (4, 1), (5, 3), (6, 0), (7, 6), (8, 7), (9, 8)]
[(1, 5), (2, 4), (3, 2), (4, 1), (5, 3), (6, 0), (7, 6), (8, 7), (9, 8)]


In [33]:
np.argsort(a)[::]

array([5, 4, 2, 1, 3, 0, 6, 7, 8], dtype=int64)

In [34]:
# 인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]

array([8, 7, 6, 0, 3, 1, 2, 4, 5], dtype=int64)

# 도전과제 Wed 0706
- np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
- np.arange(4)을 이용해서 아래와 같이 출력하세요.

# 갑자기 역행렬 구하기

In [35]:
# Q. 0 ~ 10 정수 (5,5)  행렬의 역행렬을 구한 후 두 행렬간의 행렬곱을 구하세요.
ar = np.random.randint(11,size=(5,5))
print(ar,'\n')

# 역행렬 linear_algebra. inverse 인듯
ar_r = np.linalg.inv(ar)
print(ar_r,'\n')

#행렬곱
ar_d = np.dot(ar,ar_r)
print(ar_d)

[[ 6  9  0  8  7]
 [ 6  2  2 10  9]
 [ 2  9  0  1  1]
 [ 6  5  8  6  4]
 [ 8  4  7  1  6]] 

[[ 1.18288288 -0.93063063 -1.1009009   0.13963964  0.10630631]
 [-0.18918919  0.13513514  0.28828829 -0.01801802 -0.01801802]
 [-0.4990991   0.32792793  0.4018018   0.05405405 -0.01261261]
 [ 0.24684685 -0.14774775 -0.23963964  0.14414414 -0.12252252]
 [-0.90990991  0.79279279  0.84684685 -0.26126126  0.07207207]] 

[[ 1.00000000e+00 -8.88178420e-16 -1.44328993e-15  0.00000000e+00
   1.38777878e-17]
 [ 9.99200722e-16  1.00000000e+00 -1.22124533e-15  0.00000000e+00
  -1.38777878e-17]
 [ 1.11022302e-16  0.00000000e+00  1.00000000e+00 -5.55111512e-17
   1.38777878e-17]
 [ 8.88178420e-16  0.00000000e+00 -8.88178420e-16  1.00000000e+00
   1.11022302e-16]
 [ 6.66133815e-16  0.00000000e+00 -1.11022302e-15  0.00000000e+00
   1.00000000e+00]]


# 과제 #2 Wed 0706
: 아래 가이드에 따라서 고객별 연간 구매데이터를 생성하고 아래사항을 수행하세요(관측치 1000개)

## Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

거래 번호
- id : 1 ~ 1000번 일련번호 - 개시 후 1천 건의 거래가 있었고 걍 거기에 넘버링한 거라고 이해해보자

고객별 속성 데이터
- cusno : 고객번호 1000개 랜덤
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터

- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- price_21 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성

- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21
- sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0

In [36]:
from numpy.random import randint as rri

id_ = np.array(range(1, 1001))

cusno = rri(1000, size = 1000)

gender = rri(2, size = 1000)
age = rri(81, size = 1000)
region = rri(1, 11, size = 1000)

In [37]:
product_20 = (rri(1, 4, size = 1000))*10
product_21 = (rri(1, 4, size=1000))*10
price_20 = np.random.uniform(1000.0, 50000.0, size=1000)
price_21 = np.random.uniform(1000.0, 50000.0, size=1000)
quantity_20 = rri(1, 101, size=1000)
quantity_21 = rri(1, 101, size=1000)

In [38]:
amount_20 = price_20*quantity_20
amount_21 = price_21*quantity_21

sales =np.where((amount_20 < amount_21), 1, 0)

In [39]:
data = [id_, cusno, gender, age, region, 
        product_20, product_21,price_20, price_21, quantity_20, quantity_21,
       amount_20, amount_21, sales]
sr_list = []
for i in data:
    i = pd.Series(i)
    sr_list.append(i)
type(sr_list), type(sr_list[0])

(list, pandas.core.series.Series)

In [40]:
df = pd.concat(sr_list, axis=1)
list_col = ['id_', 'cusno', 'gender', 'age', 'region', 
        'product_20', 'product_21', 'price_20', 'price_21', 'quantity_20', 'quantity_21',
       'amount_20', 'amount_21', 'sales']
dict_col = {}
for i in range(len(list_col)):
    dict_col[i] = list_col[i]
df.rename(columns = dict_col, inplace=True)
df.head()

id_  cusno  gender  age  region  product_20  product_21      price_20  \
0    1    988       0   12       2          30          10  48281.202474   
1    2    912       0   77       7          20          30   9571.800885   
2    3    827       0   15       6          10          20  32173.547996   
3    4     72       1   56       8          20          30   4961.206514   
4    5    759       1   47      10          10          30  27415.335116   

       price_21  quantity_20  quantity_21     amount_20     amount_21  sales  
0  18493.577070           70           72  3.379684e+06  1.331538e+06      0  
1  15186.963678           12           80  1.148616e+05  1.214957e+06      1  
2  14761.272650           32            6  1.029554e+06  8.856764e+04      0  
3  15454.180387           86           50  4.266638e+05  7.727090e+05      1  
4  25182.975292           76           27  2.083565e+06  6.799403e+05      0

In [41]:
len(set(cusno))

639

## Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요

## Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.