## 판다스
 - 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
 - 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
 - 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조
 - contents
    - Series(변환, 인덱스 구조, 원소 선택)
    - DataFrame(변환, 행인덱스/열이름 지정, 삭제, 선택, 추가, 변경, 전치, 인덱스 활용

#### QQ
Q. 그럼 인스턴스는 뭐로 비유해?

Q. 행렬이 벡터가 된다는 건가요?
벡터의 모음이 행렬이라는 건가? 여기서 어떤 의미 도출?

### dict -> Series

In [1]:
import pandas as pd

#딕셔너리 -> 시리즈
dict_data = {'a' : 1, 'b' : 2, 'c' : 3 }
sr = pd.Series(dict_data)
print(sr)
print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


#### Q
Q. core.series.Series는 뭐야?

### list -> Series

In [2]:
#리스트 -> 시리즈
list_data = ['2019-07-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data, index = list('abcde'))
sr

a    2019-07-02
b          3.14
c           ABC
d           100
e          True
dtype: object

### 접근

In [3]:
# 인텍스 및 값
idx = sr.index
val = sr.values

print(idx)
print(val)
type(val), type(idx)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2019-07-02' 3.14 'ABC' 100 True]


(numpy.ndarray, pandas.core.indexes.base.Index)

#### Q
sr.values 도 array 처럼 프린트되네?
dtype object 뭐임

### tuple -> Series

In [4]:
# 튜플을 시리즈로 변환
tup_data = ('kevin', '2019-07-02', '남', True)
sr = pd.Series(tup_data, index = ['이름', '생년월일', '성별', '학생여부'])
print(sr)

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object


### 접근

In [5]:
print(sr[0])
print(sr['이름'])
print(sr[[1, 2]])
# print(sr[1, 2]) 에러가 납니다.

kevin
kevin
생년월일    2019-07-02
성별               남
dtype: object


In [6]:
sr

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object

In [7]:
sr.set_axis(['name', 'bday', 'sex', 'student'], inplace=True)

In [8]:
sr

name            kevin
bday       2019-07-02
sex                 남
student          True
dtype: object

In [9]:
sr[0], sr['name'], sr.name

('kevin', 'kevin', None)

In [10]:
sr[[1, 2]]

bday    2019-07-02
sex              남
dtype: object

In [11]:
sr[1:3]

bday    2019-07-02
sex              남
dtype: object

In [12]:
import numpy as np

data = np.arange(1000, 5000, 1000)
state = ['Califonia', 'Ohio', 'Oregon', 'Texas']
obj = pd.Series(data, index = state)
obj

Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
dtype: int32

In [13]:
obj.name = 'population'
obj.index.name = 'state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [14]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

#### Q
None은 못쓰나여

In [15]:
obj.isnull().sum()

1

## 데이터프레임
 - 2차원 배열, R의 데이터프레임에서 유래
 - 열은 각각 시리즈 객체
 - 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원벡터 또는 행렬
 - 선행대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
 - 행 벡터 (1 x m 행렬)은 m원소들의 단일 행 행렬
 - 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
 - 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [16]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100, 120, size = (3, 3))
print(data, type(data))

df = pd.DataFrame(data, index = ['d1', 'd2', 'd3'], columns = ['pd', 'sales', 'inv'])
df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [17]:
# 인덱싱 : iloc  정수 인덱스, loc 이름 인덱스
print(df.iloc[1], '\n')
print(df.loc['d2'])

pd       103
sales    103
inv      107
Name: d2, dtype: int32 

pd       103
sales    103
inv      107
Name: d2, dtype: int32


In [18]:
# Q. iloc, loc 를 사용하여 107을 출력하세요

print(df.iloc[1][2])
print(df.loc['d2']['inv'], '\n')


print(df.iloc[1, 2])
print(df.loc['d2', 'inv'])

107
107 

107
107


In [19]:
# 모든 행 값 변경
df1 = df.copy()
df1

df1.loc['d3'] =0
df1

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [20]:
# 행 추가
df1.loc['d4'] = 0
df1

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [21]:
# 하나의 값만 변경
df1.iloc[0, 0] = 0
df1

pd  sales  inv
d1    0    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [22]:
# id, gender, age, region
import numpy as np
import pandas as pd

id_ = np.arange(1, 1001)
l1 = pd.Series(id_)

gender = np.random.randint(2, size = 1000)
g1 = pd.Series(gender)

age = np.random.randint(1, 101, size = 1000)
a1 = pd.Series(age)

region = np.random.randint(1, 11, size = 1000)
r1 = pd.Series(region)

df2 = pd.concat([l1, g1, a1, r1], axis = 1)
df2.rename(columns = {0 : 'id', 1 : 'gender', 2 : 'age', 3 : 'region'}, inplace = True )

df2.head()

id  gender  age  region
0   1       0   11      10
1   2       1   68      10
2   3       0    7       7
3   4       0   92      10
4   5       0  100      10

### 과제 1 _20220628  (Tue)
```
df2에 적합한 컬럼 5개를 추가하여 의미있는 
데이터셋을 만들고 그 데이터 셋의 가치를 설명
```

In [23]:
# id, gender, age, region, 
# + smoking, sleep_time, phone_time, 
# + run_record, visceral_fat

smoking = np.random.randint(2, size = 1000)
smk1 = pd.Series(smoking)

sleep_time =np. random.rand(1000)*4.0 +5.0
slp1 = pd.Series(sleep_time)

phone_time = np.random.rand(1000)*4.0 +2.0
pt1 = pd.Series(phone_time)

run_record = np.random.rand(1000)*10.0 +2.0
run1 = pd.Series(run_record)

visceral_fat = np.random.randint(1, 20, size = 1000)
vfat1 = pd.Series(visceral_fat)

df2_a = pd.concat([smk1, slp1, pt1, run1, vfat1], axis = 1)
df2_a.rename(columns = {0 : 'smoking', 1 : 'sleep_time', 2 : 'phone_time', 3 : 'run_record', 4: 'visceral_fat'}, \
             inplace = True )

df2_a_a = pd.concat([df2, df2_a], axis = 1)
df2_a_a.head()

id  gender  age  region  smoking  sleep_time  phone_time  run_record  \
0   1       0   11      10        1    5.865516    5.693768    2.771516   
1   2       1   68      10        0    8.447227    2.048842    8.348977   
2   3       0    7       7        1    8.826286    2.618158    2.207354   
3   4       0   92      10        0    7.126423    4.737676    7.342037   
4   5       0  100      10        0    7.597491    3.665865    3.614816   

   visceral_fat  
0             3  
1            13  
2            10  
3            17  
4             2

In [24]:
df3 = df2.copy()
df3.head()

id  gender  age  region
0   1       0   11      10
1   2       1   68      10
2   3       0    7       7
3   4       0   92      10
4   5       0  100      10

In [25]:
df3[0:2] = np.nan


In [26]:
df3.head()

id  gender    age  region
0  NaN     NaN    NaN     NaN
1  NaN     NaN    NaN     NaN
2  3.0     0.0    7.0     7.0
3  4.0     0.0   92.0    10.0
4  5.0     0.0  100.0    10.0

In [27]:
df3.isnull().sum().sum()

8

In [28]:
# 1 ~ 4로 구성되는 10행 5열 2차원 배열을 생성

In [29]:
np.random.seed(1)
data = np.random.randint(1, 5, size = (10,5))

In [30]:
# 배열을 리스트로 변환
list1 = data.tolist()
print(list1, type(list1))

[[2, 4, 1, 1, 4], [2, 4, 2, 4, 1], [1, 2, 1, 4, 2], [1, 3, 2, 3, 1], [3, 2, 3, 1, 4], [1, 3, 1, 2, 3], [3, 1, 4, 4, 2], [2, 4, 3, 1, 3], [2, 2, 2, 4, 4], [2, 3, 2, 2, 1]] <class 'list'>


In [31]:
df1 = pd.DataFrame(list1, columns = ['c1', 'c2', 'c3', 'c4', 'c5'])
df1.head(3)

c1  c2  c3  c4  c5
0   2   4   1   1   4
1   2   4   2   4   1
2   1   2   1   4   2

In [32]:
# 데이터프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar, type(ar))

[[2 4 1 1 4]
 [2 4 2 4 1]
 [1 2 1 4 2]
 [1 3 2 3 1]
 [3 2 3 1 4]
 [1 3 1 2 3]
 [3 1 4 4 2]
 [2 4 3 1 3]
 [2 2 2 4 4]
 [2 3 2 2 1]] <class 'numpy.ndarray'>


In [33]:
li = ar.tolist()
print(li, type(li), '\n')
dict1 = df1.to_dict('list')
print(dict1, type(dict1))

[[2, 4, 1, 1, 4], [2, 4, 2, 4, 1], [1, 2, 1, 4, 2], [1, 3, 2, 3, 1], [3, 2, 3, 1, 4], [1, 3, 1, 2, 3], [3, 1, 4, 4, 2], [2, 4, 3, 1, 3], [2, 2, 2, 4, 4], [2, 3, 2, 2, 1]] <class 'list'> 

{'c1': [2, 2, 1, 1, 3, 1, 3, 2, 2, 2], 'c2': [4, 4, 2, 3, 2, 3, 1, 4, 2, 3], 'c3': [1, 2, 1, 2, 3, 1, 4, 3, 2, 2], 'c4': [1, 4, 4, 3, 1, 2, 4, 1, 4, 2], 'c5': [4, 1, 2, 1, 4, 3, 2, 3, 4, 1]} <class 'dict'>


In [34]:
# file 생성
file_data = pd.DataFrame({ 
    'col1' : [1, 2, 3, 4, 5, 6], 
    'col2' : ['A', 'A', 'B', 'B', 'C', 'C'] 
})
file_data

col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C

In [35]:
file_data['col3'] = 'e'
file_data

col1 col2 col3
0     1    A    e
1     2    A    e
2     3    B    e
3     4    B    e
4     5    C    e
5     6    C    e

In [36]:
file_data.to_csv("dataset/file_data.csv", index = False)

In [37]:
file_data = pd.read_csv("dataset/file_data.csv")
file_data

col1 col2 col3
0     1    A    e
1     2    A    e
2     3    B    e
3     4    B    e
4     5    C    e
5     6    C    e

In [38]:
df_1 = pd.DataFrame({
    'col1' : np.array([1, 2, 3]),
    'col2' : np.array(['A', 'B', 'C'])
})
df_2 = pd.DataFrame({
    'col1' : np.array([4, 5, 6]),
    'col2' : np.array(['D', 'E', 'F'])
})

df_3 = pd.concat([df_1, df_2], axis = 1)
print(df_3, '\n')

df_4 = pd.concat([df_1, df_2])
print(df_4, '\n')

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F 

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F 



In [39]:
# 열 삭제
df_5 = df_4.copy()
df_5 = df_5.drop('col1', axis = 1)
df_5

col2
0    A
1    B
2    C
0    D
1    E
2    F

In [40]:
# 행 삭제
df_6 = df_3.copy()
df_6 = df_6.drop([0])
df_6

col1 col2  col1 col2
1     2    B     5    E
2     3    C     6    F

In [41]:
df_3.rename(index={0: 8, 1: 4, 2:5})
df_3

col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

In [42]:
df1 = file_data.copy()
df1

col1 col2 col3
0     1    A    e
1     2    A    e
2     3    B    e
3     4    B    e
4     5    C    e
5     6    C    e

In [43]:
df1[3:]

col1 col2 col3
3     4    B    e
4     5    C    e
5     6    C    e

In [44]:
df1[2:5]

col1 col2 col3
2     3    B    e
3     4    B    e
4     5    C    e

In [45]:
df1.iloc[-1]

col1    6
col2    C
col3    e
Name: 5, dtype: object

In [46]:
print(df1.loc[:, 'col1'])
print(df1.loc[:, ['col1']])

0    1
1    2
2    3
3    4
4    5
5    6
Name: col1, dtype: int64
   col1
0     1
1     2
2     3
3     4
4     5
5     6


In [47]:
print(df1.loc[:, ['col1', 'col2']])
print(df1[['col1', 'col2']])

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C
   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [48]:
print(df1.loc[1:3, ['col1', 'col3']])


   col1 col3
1     2    e
2     3    e
3     4    e


In [49]:
df1.iloc[1:3, : ]

col1 col2 col3
1     2    A    e
2     3    B    e

In [50]:
df1

col1 col2 col3
0     1    A    e
1     2    A    e
2     3    B    e
3     4    B    e
4     5    C    e
5     6    C    e

In [51]:
df1.iloc[1::2, :]

col1 col2 col3
1     2    A    e
3     4    B    e
5     6    C    e

In [52]:
import numpy as np
import pandas as pd

np.random.seed(2)
data = np.random.randint(50, 100, size = (3, 5))
df_e = pd.DataFrame(data, columns = list('abcde'))
df_e

a   b   c   d   e
0  90  65  95  58  72
1  93  68  61  90  57
2  84  99  81  61  71

In [53]:
df1 = df_e.copy()

In [54]:
df1.rename(columns = {'a' : '국어', 'b': '영어', 'c': '수학', 'd': '과학', 'e': '음악'},
           index = {0: '이상윤', 1:'강유한' , 2:'조승현' }, inplace = True)
df1

국어  영어  수학  과학  음악
이상윤  90  65  95  58  72
강유한  93  68  61  90  57
조승현  84  99  81  61  71

In [55]:
# 8행 5열 데이터프레임 생성, 인덱스명 변경, 딕셔너리 타이핑 개싫어

In [56]:
np.random.seed(3)
data = np.random.randint(10, size = (8, 5))
df_e = pd.DataFrame(data)


In [57]:
# 행이름 열이름 변경
df_e.rename(columns = {0:1, 1:2, 2:3, 3:4, 4:5},
           index = {0:'a', 1:'b', 2:'c', 3:'d', 4:'f', 5:'g', 6:'h', 7:'i'}, inplace = True)
df_e

1  2  3  4  5
a  8  9  3  8  8
b  0  5  3  9  9
c  5  7  6  0  4
d  7  8  1  6  2
f  2  1  3  5  8
g  1  8  7  8  1
h  0  5  4  1  5
i  4  7  6  0  0

In [58]:
# 3행만 출력
df_e.loc['c', :]

1    5
2    7
3    6
4    0
5    4
Name: c, dtype: int32

In [59]:
# 3행 5열의 값 출력
df_e.iloc[2, 4]

4

In [60]:
# 4열의 값을 모두 0으로 변경
df_e.iloc[:, 3] = 0
df_e

1  2  3  4  5
a  8  9  3  0  8
b  0  5  3  0  9
c  5  7  6  0  4
d  7  8  1  0  2
f  2  1  3  0  8
g  1  8  7  0  1
h  0  5  4  0  5
i  4  7  6  0  0

In [61]:
# 6행의 2, 3, 4열의 값을 조회

df_e.iloc[5, 1:4]

2    8
3    7
4    0
Name: g, dtype: int64

In [62]:
# 2열을 Series와 DataFrame으로 각각 출력
sr_c2 = pd.Series(df_e.iloc[:, 1].to_list())
print(sr_c2, type(sr_c2))

0    9
1    5
2    7
3    8
4    1
5    8
6    5
7    7
dtype: int64 <class 'pandas.core.series.Series'>


In [63]:
# 2행 3열의 값을 2행 4열의 값과 동일하게 변경
df_e.iloc[1, 2] = df_e.iloc[1, 3]
df_e

1  2  3  4  5
a  8  9  3  0  8
b  0  5  0  0  9
c  5  7  6  0  4
d  7  8  1  0  2
f  2  1  3  0  8
g  1  8  7  0  1
h  0  5  4  0  5
i  4  7  6  0  0

In [64]:
df_s = df_e.copy()
df_s

1  2  3  4  5
a  8  9  3  0  8
b  0  5  0  0  9
c  5  7  6  0  4
d  7  8  1  0  2
f  2  1  3  0  8
g  1  8  7  0  1
h  0  5  4  0  5
i  4  7  6  0  0

In [65]:
dic_ = {0:0}
rli = ['r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7']

In [66]:
for i, j in enumerate('abcdfghi') :
    dic_[j] = rli[i]

In [67]:
df_s.rename(index = dic_, inplace = True)
df_s

1  2  3  4  5
r0  8  9  3  0  8
r1  0  5  0  0  9
r2  5  7  6  0  4
r3  7  8  1  0  2
r4  2  1  3  0  8
r5  1  8  7  0  1
r6  0  5  4  0  5
r7  4  7  6  0  0

In [72]:
df1_c = df_s.sort_values(by=[1], ascending=False)
df1_c

1  2  3  4  5
r0  8  9  3  0  8
r3  7  8  1  0  2
r2  5  7  6  0  4
r7  4  7  6  0  0
r4  2  1  3  0  8
r5  1  8  7  0  1
r1  0  5  0  0  9
r6  0  5  4  0  5

In [82]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100, 120, size = (3, 3))
print(data, type(data))

df = pd.DataFrame(data, index = ['d1', 'd2', 'd3'], columns = ['pd', 'sales', 'inv'])
df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [85]:
# 행 추가
df.loc['d0'] = [1, 3, 6]
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118
d0    1      3    6

In [89]:
df.sort_index(inplace=True)
df

pd  sales  inv
d0    1      3    6
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [91]:
df.sort_values(by = 'pd' ,inplace=True)
df

pd  sales  inv
d0    1      3    6
d2  103    103  107
d3  109    119  118
d1  112    115  100

In [93]:
df1_s

NameError: name 'df1_s' is not defined

In [ ]:
# 전치
df1_t = df1_s.iloc[:5, :]
df1_t

In [ ]:
df1_t = df1_t.transpose()
df1_t

In [94]:
df

pd  sales  inv
d0    1      3    6
d2  103    103  107
d3  109    119  118
d1  112    115  100

In [100]:
df.transpose()

d0   d2   d3   d1
pd      1  103  109  112
sales   3  103  119  115
inv     6  107  118  100

In [101]:
df = df.transpose()
df

d0   d2   d3   d1
pd      1  103  109  112
sales   3  103  119  115
inv     6  107  118  100