# 20220629 Wed

In [1]:
import pandas as pd
import numpy as np

st1 = pd.Series({'국어': 100, '영어': 80, '수학': 90})
st2 = pd.Series({'국어': 90, '영어': 80, '수학': 80})
print(st1, '\n')
print(st2)


국어    100
영어     80
수학     90
dtype: int64 

국어    90
영어    80
수학    80
dtype: int64


In [2]:
# 두 학생의 과목별 점수로 사칙연산

add = st1+st2
sub = st1 - st2
mul = st1*st2
div = round((st1/st2), 2)
df = pd.concat([add, sub, mul, div], axis = 1)

In [3]:
df

0   1     2     3
국어  190  10  9000  1.11
영어  160   0  6400  1.00
수학  170  10  7200  1.12

In [4]:
result = pd.DataFrame([add, sub, mul, div], 
                      index = ['add', 'sub', 'mul', 'div'])

In [5]:
result

국어      영어       수학
add   190.00   160.0   170.00
sub    10.00     0.0    10.00
mul  9000.00  6400.0  7200.00
div     1.11     1.0     1.12

# broadcasting

In [6]:
arr = np.arange(12.).reshape(3, 4)
print(arr, '\n')
print(arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.]


In [7]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [29]:
arr_1 = np.array([2, 3, 2])
arr_1

array([2, 3, 2])

*****arr-arr_1 # 에러남

In [32]:
arr_1.T # n x 1 배열은 transpose 안됨

array([2, 3, 2])

In [35]:
np.transpose(arr_1) # 마찬가지

array([2, 3, 2])

In [36]:
arr_2 = np.array([[2], [3], [2]])   # 이렇게 하면 됨
arr_2

array([[2],
       [3],
       [2]])

In [38]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
arr-arr_2

array([[-2., -1.,  0.,  1.],
       [ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.]])

# DataFrame과 Series간 연산

In [39]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3), 
                     columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [9]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [40]:
frame - series # broad casting

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [41]:
# 열만 있을때 broad casting?  일단 안됌

In [42]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [43]:
s = frame['b'] # 안됨
s

Utah      0.0
Ohio      3.0
Texas     6.0
Oregon    9.0
Name: b, dtype: float64

In [44]:
frame - s 

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [47]:
df_s = pd.DataFrame([s]) # 안됨
df_s

Utah  Ohio  Texas  Oregon
b   0.0   3.0    6.0     9.0

In [49]:
frame - df_s

Ohio  Oregon  Texas  Utah   b   d   e
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
b        NaN     NaN    NaN   NaN NaN NaN NaN

In [52]:
df_s = df_s.transpose()
df_s

b
Utah    0.0
Ohio    3.0
Texas   6.0
Oregon  9.0

In [54]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [53]:
frame - df_s

b   d   e
Utah    0.0 NaN NaN
Ohio    0.0 NaN NaN
Texas   0.0 NaN NaN
Oregon  0.0 NaN NaN

In [11]:
frame + frame

b     d     e
Utah     0.0   2.0   4.0
Ohio     6.0   8.0  10.0
Texas   12.0  14.0  16.0
Oregon  18.0  20.0  22.0

커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map함수 : DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용
- apply함수 : 커스텀 함수를 사용하기 위해 DataFrame에서 복수 개의 컬럼이 필요하다면, apply함수를 사용
- applymap함수 : DataFrame클래스의 함수이긴 하나, 위의 apply함수처럼 각 row(axis=1)나 각 column(axis=0)별로 
작동하는 함수가 아니라, 각 요소(element)별로 작동  
마치 선형대수에서 벡터에 스칼라를 연산하면, 벡터의 요소 하나하나에 해당 연산을 해주는 것처럼(elementwise) 
적용하는 DataFrame의 각 요소마다 커스텀 함수(반드시 Single vaule를 반환하는)를 수행한다고 보면 된다. 
applymap에 인자로 전달하는 커스텀함수가 Single value로부터 Single value를 반환한다는 점이 중요하다

In [55]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [64]:
f = lambda x: x.max() - x.min()
frame.apply(f), type(frame.apply(f))   # dataframe을 넣어 series가 나옴, default는 같은 column내에서

(b    9.0
 d    9.0
 e    9.0
 dtype: float64,
 pandas.core.series.Series)

In [65]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [66]:
frame.apply(f, axis = 1) # 1 대신 'columns' 사용도 가능

Utah      2.0
Ohio      2.0
Texas     2.0
Oregon    2.0
dtype: float64

# 여러값을 가진 Series 반환

In [67]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [68]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])
frame.apply(f)

b     d     e
min  0.0   1.0   2.0
max  9.0  10.0  11.0

In [70]:
frame.apply(f, axis=1)

min   max
Utah    0.0   2.0
Ohio    3.0   5.0
Texas   6.0   8.0
Oregon  9.0  11.0

# 과제_ 20220629 Wed

최대한 복잡한 사용자 함수를 생성한 후 dataframe에 적용하여 결과를 출력하세요. 가치~~ 유용~~~ dataframe도 알아서 만들고~~

In [19]:
import pandas as pd
df_p = pd.read_csv('dataset/penguin.csv', encoding = 'cp949')
df_p.head(n = 10)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   
6  Adelie  Torgersen            38.9           17.8              181.0   
7  Adelie  Torgersen            39.2           19.6              195.0   
8  Adelie  Torgersen            34.1           18.1              193.0   
9  Adelie  Torgersen            42.0           20.2              190.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE  
5       3650.0    MALE  
6       3625.0  FEMALE  
7       4675.0    MALE  
8       3475.0     NaN  
9       4250.0     NaN

In [20]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


```
아델리 펭귄만 뽑은 다음, 부리 크기size =  length*depth 해서 열추가후 Dream섬 부리크기 min max ave med
```

In [21]:
islands = set(df_p.island)
print(islands)

species = set(df_p.species)
print(species)

{'Biscoe', 'Dream', 'Torgersen'}
{'Gentoo', 'Adelie', 'Chinstrap'}


In [22]:
df_ade = df_p[df_p.species == 'Adelie']

In [23]:
import numpy as np
df_ob = pd.concat([df_ade.island, df_ade.bill_depth_mm* df_ade.bill_length_mm], axis = 1)
df_ob = df_ob.rename(columns = {0: 'bill_size'})
df_ob = df_ob.dropna()
df_ob.head()

island  bill_size
0  Torgersen     731.17
1  Torgersen     687.30
2  Torgersen     725.40
4  Torgersen     708.31
5  Torgersen     809.58

In [24]:
def mmam(x):
    return pd.Series([min(x), max(x), np.average(x), np.median(x)], index = ['min', 'max', 'avg', 'med'])

In [25]:
df_od= df_ob[df_ob.island == 'Dream'].drop('island', axis = 1)
df_od.apply(mmam)

bill_size
min  497.550000
max  896.760000
avg  704.120357
med  705.475000

In [26]:
df_od.describe()

bill_size
count   56.000000
mean   704.120357
std     76.377655
min    497.550000
25%    658.987500
50%    705.475000
75%    746.842500
max    896.760000

# format

In [74]:
frame_1 = frame.copy()

In [80]:
frame_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Utah to Oregon
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   b       4 non-null      float64
 1   d       4 non-null      float64
 2   e       4 non-null      float64
dtypes: float64(3)
memory usage: 300.0+ bytes


In [81]:
format_ = lambda x: '%.2f'%x
frame_2 = frame_1.applymap(format_)
frame_2, frame_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Utah to Oregon
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   b       4 non-null      object
 1   d       4 non-null      object
 2   e       4 non-null      object
dtypes: object(3)
memory usage: 300.0+ bytes


(           b      d      e
 Utah    0.00   1.00   2.00
 Ohio    3.00   4.00   5.00
 Texas   6.00   7.00   8.00
 Oregon  9.00  10.00  11.00,
 None)

In [82]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [86]:
frame_a = pd.DataFrame(np.array([[1.23, 2.34, 3.45], [4.56, 5.67, 6.78]]))
frame_a

0     1     2
0  1.23  2.34  3.45
1  4.56  5.67  6.78

In [87]:
format_2 = lambda x: round(x, 1)
frame_3 = frame_a.applymap(format_2)
frame_3, frame_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       2 non-null      float64
 1   1       2 non-null      float64
 2   2       2 non-null      float64
dtypes: float64(3)
memory usage: 176.0 bytes


(     0    1    2
 0  1.2  2.3  3.5
 1  4.6  5.7  6.8,
 None)

In [88]:
frame_a

0     1     2
0  1.23  2.34  3.45
1  4.56  5.67  6.78

In [90]:
frame_a = frame_a.round(1)
frame_a

0    1    2
0  1.2  2.3  3.4
1  4.6  5.7  6.8

In [92]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [93]:
frame['e'].map(format_)

Utah       2.00
Ohio       5.00
Texas      8.00
Oregon    11.00
Name: e, dtype: object

# END